### ISSUE TITLE
App crash when deploying to an iOS device

### ISSUE THREAD

**Issue by cptdanko** [satheeshwaran/NotificationsforiOS8#1]
So I cloned the project and deployed it to my iPhone 5, running iOS 7.1 (I obviously changed the deployment target of the project to 7.1 from 8.1). So the app crashes on starting it?

I have an iPhone 6 too with iOS 8.1. and on that it works just fine, as you would expect it. So I did have this issue in the app I am making, so I cloned this repo, to see if this solves this code base solves this problem? but unfortunately it does not at this point, would you know why?

**Comment by satheeshwaran** [comment]
The project uses an iOS 8 feature, interactive notifications and the first line in appDelegate.swift is this

```
  application.registerUserNotificationSettings(UIUserNotificationSettings(forTypes:     UIUserNotificationType.Sound | UIUserNotificationType.Alert |
        UIUserNotificationType.Badge, categories: nil))
```

which uses the class UIUserNotificationSettings which is available only from iOS 8.

**Comment by cptdanko** [comment]
ok that makes sense, since I am still new to iOS programming a lot of the problems I face are not very hard, just lack of knowledge on my part. So I blog about it, here's one example,
http://captaindanko.blogspot.com.au/2014/12/knowing-which-notification-brought-my.html
Only if you do have time and you know it, then do let me know how to get user permission for notifications, such that it works on both iOS 7 and iOS 8.

**Comment by RaviMalviya** [comment]
replace application delegate method name.
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject : AnyObject]?) -> Bool {
}
